### ISSUE TITLE
i'm going out of the car with new seatbelt

### ISSUE THREAD

**Issue by fantomeus** [TehRamsus/Seatbelt#1]
i post you a video from the script, no error in F8 and console

https://streamable.com/mocd2x

have you got any ideas to fix that ?

**Comment by TehRamsus** [comment]
Hello! What is that vehicle, what you just use? I will try it :)

**Comment by fantomeus** [comment]
Hello it was baller6

**Comment by TehRamsus** [comment]
Have you tried other cars? It's known bug, seatbelt not working with all vehicles for some reason.

**Comment by fantomeus** [comment]
i've tried now with modded vehicle and look like good but it was a really problem i've not only modded car lmao !! and all native car look not found :/ iv'e tried sultan too same problem

**Comment by TehRamsus** [comment]
Hey! Download or clone latest version of this repo, and try it. Try first change speed value in config.

**Comment by fantomeus** [comment]
thx for new release, first try not found more :'( what do you want i change in speed ?

**Comment by TehRamsus** [comment]
I tried vanilla vehicles, and all works good. I must continue solve this problem :)

**Comment by fantomeus** [comment]
maybe a little suggest, do you try with onesync infinity ? maybe it was the problem ?
