### ISSUE TITLE
Blinker image not sync with the loop sound

### ISSUE THREAD

**Issue by recso** [TehRamsus/Seatbelt#4]
So yesterday i installed the new Seatbelt and it was working fine, and today i decided to edit it so the players can hear the loop sound and see the blinker in the bottom of the screen aswell,
When edited the "**Config.LoopSound**" from "**false**" to "**true**" the blinker image blinks once and the sound continue looping, its like the sound talking priority.
Also i've managed to change sound and image and yet the same as before.

**Comment by TehRamsus** [comment]
Hello!

Yeah, because that sound is about 3 seconds long. I will fix that later.

**Comment by recso** [comment]
@TehRamsus 
no, the sound and the image both starts working after like two bips of the sound the image stops popping up and the sound keeps bipping.
