### ISSUE TITLE
Seatbelt Sound

### ISSUE THREAD

**Issue by StraightQuondo** [TehRamsus/Seatbelt#5]
Others can hear the seatbelt around you

**Comment by aidenszolosi** [comment]
This isn't a bug, I actually haven't noticed this myself. It's useful in RP because a police officer could ask you to turn off your engine and unbuckle. If the player wishes to takeoff then they better buckle up, which is an audible noise and clue for officers.

**Comment by recso** [comment]
> Others can hear the seatbelt around you

i'm not sure if thats possible, but i've thought like that too before, but if you take a closer look on the client.lua you will find out that there is a slight delay of the loopsound after you go out from your car.

**Comment by TehRamsus** [comment]
No, other players can't hear that sound :D

**Comment by StraightQuondo** [comment]
also when I get out of the car sometimes the seatbelt sound still plays not sure if that was fixed or not
