### ISSUE TITLE
Seatbelt icon comes back

### ISSUE THREAD

**Issue by Thunderqz** [TehRamsus/Seatbelt#6]
If you put on your seatbelt, and then open your pause menu / map then exit it the seatbelt icon will show up again even though you have your seatbelt still on. Its just a visual bug

**Comment by recso** [comment]
this is a bug, give him some time to fix it, there's also another bug with the synchronization of the sound and the icon he said he will fix it later.

**Comment by TehRamsus** [comment]
Hello! Yeah, i will rework that icon and sound sync.

**Comment by tieumieu90** [comment]
did it fix yet? and also it will jump out if my car hit it hard
